language: node_js
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules
#before_install:
#  - "yarn install"
install:
  - yarn install
  # puppeteer's install script downloads Chrome
script:
  - yarn test
